Add script to open github prs.

diff --git a/dot_zshrc.tmpl b/dot_zshrc.tmpl
--- a/dot_zshrc.tmpl
+++ b/dot_zshrc.tmpl
@@ -68,3 +68,23 @@ if [ -f ~/.okrepo/ok.sh ]; then
 fi
 
 complete -o nospace -C /usr/local/bin/vault vault
+
+# Open the Pull Request URL for your current directory's branch (base branch defaults to master)
+function openpr() {
+  remote=${$1:-origin}
+  github_url=`git remote -v | awk "/^${remote}.*\\(fetch\\)$/{print \$2}" | sed -Ee 's#(git@|git://)#https://#' -e 's@com:@com/@' -e 's%\.git$%%'`;
+  branch_name=`git symbolic-ref HEAD | cut -d"/" -f 3,4`;
+  pr_url=$github_url"/compare/master..."$branch_name
+  open $pr_url;
+}
+
+# Run git push and then immediately open the Pull Request URL
+function gpr() {
+  git push origin HEAD
+
+  if [ $? -eq 0 ]; then
+    openpr
+  else
+    echo 'failed to push commits and open a pull request.';
+  fi
+}
